FFmpeg Quirks in LPMS
livepeer/lpms pull request #275
Opened 2021-11-29 09:07 UTC by oscar-davids

This document outlines how LPMS tweaks FFmpeg transcoding pipeline to address some specific problems.

2021-11-30 10:24 UTC, jailuthra requested changes
Would be good to have links and refrences to issues and PRs around these topics, as a time-saver for engineers who on-board later on.

2021-11-30 10:24 UTC, jailuthra commented on QUIRKS.md
> +ii. OR use SETPTS filter in the filtergraph before FPS filter, which would do the same thing.
We should remove this from the documentation, as we did not take the approach of SETPTS filter due to reasons mentioned here https://github.com/livepeer/lpms/pull/201#issuecomment-664853222

2021-11-30 10:24 UTC, jailuthra commented on QUIRKS.md
> +
We should probably add links to the code snippet that implements this.
We can also note the fact that the filter gives up after sending `SENTINEL_MAX` packets, which is a pre-processor constant defined as `5` for now.

2021-11-30 10:24 UTC, jailuthra commented on QUIRKS.md
> +We bypass the usual transcoding process for audio-only segments and just return them back. To do this, we check if video frame is present, and if not present just copy the frames to the output as it
While the by-pass check code is still implemented in LPMS we no longer use this function on the transcoder directly, or set the 'copy' encoder. https://github.com/livepeer/lpms/blob/46f7030c62d91d5f74b02bfa13dca42eb8ad8fa5/ffmpeg/extras.c#L110-L117 

We instead moved the calling logic on the Broadcaster side in https://github.com/livepeer/go-livepeer/pull/1933 and the document should reflect that.

2021-12-03 10:41 UTC, cyberj0g commented
Amazing write-up, @jailuthra @oscar-davids! Hijacking this branch to add a small section on reusing transcoding session with HW codecs. I believe much of the information on this is already in the document.

2021-12-06 08:21 UTC, merged