Fix the failure of TestTranscoder_DetectionFreq in CircleCI
livepeer/lpms pull request #306
Opened 2022-02-11 02:54 UTC by JamesWanglf

- Before we run `TestTranscoder_DetectionFreq` function, we need to download `tasmodel.pb` first.
- We need to set the library path for the Tensorflow linking in env variables.
- To build the ffmpeg with libtensorflow, `experimental` should be contained in BUILD_TAGS.

2022-02-16 15:28 UTC, cyberj0g requested changes

2022-02-16 15:28 UTC, cyberj0g commented on .circleci/config.yml
> +            wget https://github.com/livepeer/livepeer-ml/releases/download/v0.3/tasmodel.pb
Given `lpms` is not released separately, maybe not pin the version here and link to [latest](https://github.com/livepeer/livepeer-ml/releases/latest/download/tasmodel.pb) release, so we don't have to update CI job for every new version of the model?

2022-02-16 15:28 UTC, cyberj0g commented on .circleci/config.yml
> +            mv tasmodel.pb ./ffmpeg
Maybe download right to destination dir e.g. `wget URL -P ffmpeg`

2022-02-22 14:25 UTC, JamesWanglf commented
If I disable `restore_cache` step, all tests will be passed.
If I enable this step, test will be failed at Test_DetectionFreq method. I guess this is occurred because the cached ffmpeg will be used, rather than the latest checkout.

2022-02-25 06:57 UTC, oscar-davids approved these changes
LGTM!

2022-02-25 10:53 UTC, cyberj0g commented
LGTM!

2022-02-25 10:53 UTC, cyberj0g approved these changes

2022-02-25 12:35 UTC, merged