evaluate same audio data with chi-distance
livepeer/lpms pull request #352
Opened 2022-07-22 10:32 UTC by oscar-davids

2022-07-22 11:03 UTC, cyberj0g reviewed
Looks good! Could you provide some context on why we can't just compare audio packets by data or hash, or maybe it was already discussed somewhere?

2022-07-22 13:00 UTC, oscar-davids commented on ffmpeg/extras.c
> +#define MIN_AUDIO_CHI_DIS 500.0
We have already collected audio mismatch renditions and based on these data, I got this threshold.

2022-07-22 15:27 UTC, cyberj0g commented
I see, thanks for adding the explanation. My concern is that distribution-based metric doesn't give any account to the temporal structure of the signal, so it's very easy to construct a sample, which would pass verification, while having all audio packets mixed. If we know that the cause of this fuzzy verification issue is some packet missing in the rendition, maybe it's best to either explicitly allow some packet loss, or use metric which accounts for observation sequence? For former, we'd need to store per-packet MD5 sums and skip source packets without match, until packet loss threshold is reached. Not sure how practical it is to implement right now, maybe merge chi-squared comparison, and create an issue for later.
WDYT @oscar-davids @yondonfu @thomshutt

2022-07-25 13:34 UTC, yondonfu commented
> My concern is that distribution-based metric doesn't give any account to the temporal structure of the signal, so it's very easy to construct a sample, which would pass verification, while having all audio packets mixed.

If this is the case, then I advocate for estimating the effort required for Ivan's per-packet MD5 sum check with packet loss threshold approach and if it is <= 1 day of work implement it. @oscar-davids can you comment on whether you think Ivan's suggestion would work and the estimation of effort required?

2022-07-25 15:05 UTC, oscar-davids commented
I agree with Ivan's opinion that chi-distance is weaker than MD5 or hash for security strength. I will implement it with MD5 per audio packet and it will take less than one day.

2022-07-26 15:23 UTC, AlexKordic approved these changes
Well done!

2022-07-26 15:23 UTC, AlexKordic commented on ffmpeg/extras.c
> +  int       *pmd5array;
Can we use `int32_t` here instead of `int`?

2022-07-27 09:49 UTC, cyberj0g requested changes
Sorry for nitpicking again, but wouldn't such approach allow an attacker to shuffle packets inside the 10% bins to get fully corrupted audio, which verifies successfully? If the issue we are addressing is 'some audio packets infrequently missing from rendition', we can have an algorithm like that (pseudocode):
```
bool isValid(info1, info2)
{
    // given info1 is source, info2 is rendition
    int mismatchCount = abs(info1->apacketcount - info2->apacketcount);
    int i, j = 0;
    while (mismatchCount < maxMismatch && i < info1->apacketcount && j < info2->apacketcount)
          i++;
          if(info1->hashes[i] != info2->hashes[j]){
               // hash mismatch - rendition packet is probably missing
              mismatchCount++;
              continue;
          }
          j++;
    }
    return mismatchCount < maxMismatch
}
```
If our issue is closer to arbitrary incomplete permutations of audio packets in renditions, then enforcing a weak sequential constraint like in the PR is probably good enough for now.

2022-07-27 13:37 UTC, oscar-davids commented
That's a good point.
However, since random packets are dropped with both renditions from Ts the current implementation works better realistically.

2022-07-28 07:33 UTC, cyberj0g commented
Got it, let's go with this workaround for now, then. I've created an [issue](https://github.com/livepeer/go-livepeer/issues/2542), so we wouldn't forget to resolve this eventually.

2022-07-28 07:33 UTC, cyberj0g approved these changes

2022-07-28 08:45 UTC, merged